# name: Unit Tests
# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]
# jobs:
#   test:
#     timeout-minutes: 10
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: oven-sh/setup-bun@v1
#         with:
#           bun-version: latest
#       - name: Install dependencies
#         run: bun install
#       - name: Run unit tests
#         run: bun test:unit
#       - uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: test-results
#           path: coverage/
#           retention-days: 30
